exclude:
  - cards/node_modules
  - cards/src
  - cards/package.json
  - cards/pnpm-lock.yaml
  - cards/tsconfig*.json
  - cards/vite.config.ts
  - test2/node_modules
  - test2/src
  - test2/package.json
  - test2/pnpm-lock.yaml
  - test2/tsconfig*.json
  - test2/vite.config.ts
  - "*.md"
