// Edit this array to change the animated text lines.
const TEXTS = [
  "Modern organizations have workflow systems.<br/>They lack decision systems.",
  "Revisit and revise commitments<br/>before regret becomes expensive.",
  "Your company instruments the work.<br/>Does it instrument the judgment that authorizes it?",
  "Synthetic skin-in-the-game<br/>for an actor that has no skin.",
  "Accountability architectures<br/>for non-accountable agents.",
  "Show us the last five consequential decisions<br/>your organization made.",
  "Recognize when prior decisions no longer deserve the resources allocated to them.",
  "Price, supervise, and shorten the half-life<br/>of bad commitments.",
  "Supervision for the unsupervised.",
  "Make midcourse corrections<br/>with governed overrides.",
  "What is your organization learning?",
  "What do your biggest commitments<br/>misleadingly assume?",
  "Every consequential decision in your company is made by a manager or an AI.<br/>Neither is currently instrumented for learning.",
  "Make prior judgment actionable.",
  "Institutional memory for<br/>why you made your biggest decisions.",
  "What do your biggest commitments assume<br/>that is no longer true?",
  "Improve judgment under uncertainty.",
  "Decision discipline<br/>for human, AI, and hybrid teams.",
];
